name: ChallagePlugin
author: Nirvanacw Team
version: 1.0
main: de.nirvanacw.main.TheChallange
commands:
  start:
    description: dieser Command Startet die Challange
    usage: /start
  pause:
    description: dieser Commadn Pausiert und Entpasiert die Challange
    usage: /pause